######################## default configuration ####################
baseURL = "https://github.com/AlexMaldon/website"
title = "PHR | Data Scientist "
theme = "Theme Somrat"
# disable language
# disableLanguages = [] # disable language from here
canonifyURL = "true"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/fontawesome/fontawesome.min.css"
[[params.plugins.css]]
link = "plugins/hover/hover.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "#home"
weight = 1

[[menu.main]]
name = "About me"
URL = "#about"
weight = 2

[[menu.main]]
name = "Skills"
URL = "#service"
weight = 3

[[menu.main]]
name = "Projects"
URL = "#portfolio"
weight = 4

# [[menu.main]]
# name = "Testimonial"
# URL = "#testimonial"
# weight = 5

[[menu.main]]
name = "Contact"
URL = "#contact"
weight = 6


#################### default parameters ################################
[params]
logo ="images/logo.png"
desktop-logo = "images/logo.png"
logo_light = "images/logo.png"
logo_dark = "images/logo-dark.png"
# Meta data
description = "This is meta description"
author = "PHR"
# contact form action
contact_form_action = "https://formspree.io/f/xoqpbqrq" # contact form works with https://formspree.io
# Google analytics
google_analytics_id = "" # your id

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.
  
############################# social site ########################
[[params.social]]
icon = "fab fa-linkedin" # fontawesome icon 4.7.0 : https://fontawesome.com/v5.0.0/icons/
link = "https://www.linkedin.com/in/pilarhernanz/"

[[params.social]]
icon = "fab fa-twitter-square" # fontawesome icon 4.7.0 : https://fontawesome.com/v5.0.0/icons/
link = "https://twitter.com/pilarhrod"

[[params.social]]
icon = "fab fa-github" # fontawesome icon 4.7.0 : https://fontawesome.com/v5.0.0/icons/
link = "https://github.com/AlexMaldon"



# [[params.social]]
# icon = "fa fa-instagram" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
# link = "https://www.instagram.com/somrat_sorkar/"

# [[params.social]]
# icon = "fa fa-facebook-f" # fontawesome icon 4.7.0 : https://fontawesome.com/v4.7.0/icons/
# link = "https://www.facebook.com/somrat.mac"


################################### English language #####################################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [somrat](https://somrat.netlify.com)"


################################### Spanish language #####################################
[Languages.es]
languageName = "Español"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 2
home = "Homepage"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [somrat](https://somrat.netlify.com)"


################################## French language #####################################
#[Languages.fr]
#languageName = "Fr"
#languageCode = "fr-fr"
#contentDir = "content/french"
#weight = 3
#home = "Accueil"
## copyright
#copyright = "Copyright &copy; 2020 a hugo theme by [somrat](https://somrat.netlify.com)"